### ISSUE TITLE
Node_modules nested core folder causes identifiers conflict

### ISSUE THREAD

**Issue by anyandallart** [fullcalendar/fullcalendar-angular#226]
I have a windows machine and am using Angular 8. When I ng new and create a new project and run the install commands (npm install --save @fullcalendar/angular @fullcalendar/core @fullcalendar/daygrid), what it does is puts a copy of @fullcalendar/core inside of the main node_modules folder, and it also puts a copy of @fullcalendar/core inside of @fullcalendar/angular/node_modules

So the file structure ends up looking like:
@fullcalendar
....angular
........node_modules
............@fullcalendar
................**core**
....**core**
....daygrid

When I run ng serve, I get an error: "node_modules/@fullcalendar/core/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ElementContent, DurationInp
ut, DateMarker, DAY_IDS, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, NamedTimeZoneImpl...." with a lot of other items listed.

I'm able to solve this error by deleting the second copy of core at "@fullcalendar/angular/node_modules/@fullcalendar/core". After I delete that folder, there are no errors in my build and it runs fine. Although this works I imagine this isn't a good practice. 

Is there something wrong with my setup? I have been using npm on windows for a while and I haven't had this particular issue before when using other libraries. Any help would be greatly appreciated. If you would prefer for me to post this elsewhere feel free to let me know, I wanted to double check first this wasn't something related to fullcalendar specifically or if there was a really easy answer. Thank you!

**Comment by arshaw** [comment]
@anyandallart this should be fixed if you upgrade to v4.3.1
Please see: https://github.com/fullcalendar/fullcalendar/issues/4968

**Comment by anyandallart** [comment]
@arshaw I upgraded to 4.3.1 and unfortunately still have the same problem. The image below shows 3 things: 1) the duplicate versions of core on the left, 2) the current version of 4.3.1 in my package.json in the middle, and 3) the error output for my angular app. 

Once I remove the second nested core folder everything works. Not sure what the situation is.

![image](https://user-images.githubusercontent.com/1707057/64490928-db851400-d227-11e9-85bd-aaa12ce37c76.png)

**Comment by arshaw** [comment]
@anyandallart you might need to completely delete node_modules first and then reinstall all deps. or just do `npm ci`

**Comment by anyandallart** [comment]
I uninstalled and reinstalled and that worked (I imagine "npm ci" would have done the same). Thank you very much for your assistance here!

**Comment by TokerX** [comment]
Still an issue...

Fullcalendar version:

    "@fullcalendar/angular": "^5.3.1",
    "@fullcalendar/core": "^5.3.0",
    "@fullcalendar/daygrid": "^5.3.2",
    "@fullcalendar/interaction": "^5.3.1",
    "@fullcalendar/list": "^5.3.1",
    "@fullcalendar/timegrid": "^5.3.1",

/node_modules/@fullcalendar/angular/node_modules/@fullcalendar containing common & core
/node_modules/@fullcalendar/daygrid/node_modules/@fullcalendar containing common
/node_modules/@fullcalendar/interaction/node_modules/@fullcalendar containing common
/node_modules/@fullcalendar/list/node_modules/@fullcalendar containing common
/node_modules/@fullcalendar/timegrid/node_modules/@fullcalendar containing common

Each time I restart the server it complains about one of them, so each time I deleted the nested node_modules folder and it worked. Last time it just broke the whole thing. Reinstalled fullcalendar, now it's complaining about /node_modules/@fullcalendar/common/main's LocaleInput[] not being assignable to /node_modules/@fullcalendar/angular/node_modules/@fullcalendar/common/main's LocaleInput[]...

Npm ci didn't resolve anything, still nested folders, still the same error. And sure I could just delete those folders again, but at some point I'm sure it'll just break the whole thing again. ¯\_(ツ)_/¯
